# Garage Door Example - https://esphome.io/cookbook/garage-door
# Control a garage door which uses a momentary-button (like a doorbell)

substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: garage_door
  friendly_name: Garage Door
  button_delay: 150ms
  ip_address: !secret garage_door_ip


esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  platform: ESP8266
  board: d1_mini


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1


# web_server:
#   port: 80
#   # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


cover:
  - platform: template
    # https://esphome.io/components/cover/template
    name: ${friendly_name}
    id: ${device_name}
    lambda: |-
      if (id(sensor).state) {
        return cover::COVER_OPEN;
      } else {
        return cover::COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: momentary_button
    close_action:
      - switch.turn_on: momentary_button
    stop_action:
      - switch.turn_on: momentary_button


binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio
    pin: 
      number: GPIO16   # D0   sensor uses D0 & 3.3v
      mode: INPUT_PULLDOWN_16
      inverted: True   # may need to remove this depending on where your sensor is located
    id: sensor
    internal: True
    


switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    id: relay
    pin: GPIO5   # D1
    restore_mode: ALWAYS_OFF
    internal: True

  - platform: template
    # https://esphome.io/components/switch/template
    id: momentary_button
    turn_on_action:
      - switch.turn_on: relay
      - delay: ${button_delay}
      - switch.turn_off: relay
    internal: True
